services:
  - type: web
    name: BookSwap
    env: docker
    repo: https://github.com/vandaszabo/BookSwap/BookSwap
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_CONNECTIONSTRING
        sync: true
      - key: ASPNETCORE_ADMINEMAIL
        sync: true
      - key: ASPNETCORE_ADMINPASSWORD
        sync: true
      - key: ASPNETCORE_ISSUERSIGNINGKEY
        sync: true
      - key: ASPNETCORE_VALIDISSUER
        sync: true
      - key: AWS_ACCESSKEY
        sync: true
      - key: AWS_SECRETKEY
        sync: true
      - key: AWS_BUCKET_NAME
        sync: true
      - key: FRONTEND_DOMAIN
        sync: true

  - type: web
    name: BookSwap-frontend
    env: docker
    repo: https://github.com/vandaszabo/BookSwap/bookswap-frontend
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REACT_APP_BACKEND_URL
        sync: true

  - type: postgres
    name: BookSwapWebAppDb
    env: managed
    plan: standard
