services:
  - type: web
    name: BookSwap
    env: docker
    repo: https://github.com/vandaszabo/BookSwap/BookSwap
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_CONNECTIONSTRING
        sync: true  # Fetch this value from Render's environment variables settings or manually set it

  - type: web
    name: BookSwap-frontend
    env: docker
    repo: https://github.com/vandaszabo/BookSwap/bookswap-frontend
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: REACT_APP_BACKEND_URL
        sync: true

  - type: postgres
    name: BookSwapWebAppDb
    env: managed
    plan: standard
