name: Composed Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-composed:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Backend Docker image
      run: docker build -t bookswap:latest ./BookSwap

    - name: Build the Frontend Docker image
      run: docker build -t bookswap-frontend:latest ./bookswap-frontend

    - name: Docker Compose
      run: docker-compose up -d

